name: CrazyCrates
main: "${group}.CrazyCrates"
author: BadBones69
version: ${version}
api-version: 1.18
description: ${description}

softdepend: [HolographicDisplays, DecentHolograms, MVdWPlaceholderAPI, PlaceholderAPI]

commands:
  crazycrates:
    description: Opens the GUI.
    aliases: [cc, ccrate, crazycrate, crate, crates]
  key:
    description: Views the amount of keys you/others have.
    aliases: [keys]

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.21