name: CrazyCrates
main: "${group}.CrazyCrates"
author: BadBones69
version: ${version}
api-version: 1.18
description: ${description}

softdepend: [HolographicDisplays, DecentHolograms, MVdWPlaceholderAPI, PlaceholderAPI]

commands:
  crazycrates:
    description: Opens the GUI.
    aliases: [cc, crazycrate, crate, crates]
  key:
    description: Views the amount of keys you/others have.
    aliases: [keys]

permissions:
  crazycrates.command.player.help:
    default: op
    children:
      crazycrates.command.player.key: true

  crazycrates.command.player.menu:
    default: op

  crazycrates.command.admin.additem:
    default: op

  crazycrates.command.admin.preview:
    default: op

  crazycrates.command.admin.list:
    default: op
    children:
      crazycrates.command.admin.teleport: true

  crazycrates.command.admin.open:
    default: op

  crazycrates.command.admin.open.others:
    default: op
    children:
      crazycrates.command.admin.open: true

  crazycrates.command.player.key:
    default: op

  crazycrates.command.player.key.others:
    default: op
    children:
      crazycrates.command.player.key: true

  crazycrates.command.admin.takekey:
    default: op
    children:
      crazycrates.command.player.transfer: true

  crazycrates.command.player.transfer:
    default: op

  crazycrates.command.admin.forceopen:
    default: op
    children:
      crazycrates.command.admin.open: true
      crazycrates.command.admin.open.others: true

  crazycrates.command.admin.teleport:
    default: op

  crazycrates.command.admin.givekey:
    default: op

  crazycrates.command.admin.giveall:
    default: op
    children:
      crazycrates.command.admin.givekey: true
      crazycrates.command.admin.takekey: true

  crazycrates.command.admin.set:
    default: op

  crazycrates.command.admin.setmenu:
    default: op
    children:
      crazycrates.command.admin.set: true

  crazycrates.command.admin.reload:
    default: op

  crazycrates.command.admin.debug:
    default: op

  crazycrates.command.admin.convert:
    default: op

  crazycrates.command.admin.schematic:
    default: op
    children:
      crazycrates.command.admin.schematic.save: true
      crazycrates.command.admin.schematic.set: true

  crazycrates.command.admin.schematic.save:
    default: op

  crazycrates.command.admin.schematic.set:
    default: op

  crazycrates.command.admin.help:
    default: op
    children:
      crazycrates.command.admin.reload: true

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.21
  - cloud.commandframework:cloud-core:1.7.0