[versions]

# Paper Team
paper = "1.19.2-R0.1-SNAPSHOT"

# Triumph Team
triumph-cmd-bukkit = "2.0.0-SNAPSHOT"
triumph-gui-bukkit = "3.1.2"

# Minecraft Team
mc-brigadier = "2.2"

# Bukkit
bukkit-bstats = "3.0.0"

# Holograms
holographic-displays = "2.4.9"
decent-holograms = "2.7.2"

# Placeholders
placeholder-api = "2.11.2"

# Misc Libraries
nbt-api = "2.10.0"
vault-api = "1.7"

[libraries]

# Paper Team
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Triumph Team
triumph-cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version.ref = "triumph-cmd-bukkit" }
triumph-guis = { module = "dev.triumphteam:triumph-gui", version.ref = "triumph-gui-bukkit" }

# Minecraft
mc-brigadier = { module = "me.lucko:commodore", version.ref = "mc-brigadier"}

# Bukkit
bukkit-bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bukkit-bstats" }

# Holograms
holographic-displays = { module = "com.gmail.filoghost.holographicdisplays:holographicdisplays-api", version.ref = "holographic-displays" }
decent-holograms = { module = "com.github.decentsoftware-eu:decentholograms", version.ref = "decent-holograms" }

# Placeholders
placeholder-api = { module = "me.clip:placeholderapi", version.ref = "placeholder-api" }

# NBT API Libraries
nbt-api = { module = "de.tr7zw:nbt-data-api", version.ref = "nbt-api" }

# Misc Libraries
vault-api = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault-api" }