name: Publish to Hangar and Modrinth
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'CrazyCrates'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true

      - name: Gradle Properties Import.
        shell: bash
        run: cat gradle.properties >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Publish
        env:
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        #run: ./gradlew assemble modrinth publishAllPublicationsToHangar --stacktrace
        run: ./gradlew assemble modrinth --stacktrace