name: Upload
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle Properties Import.
        shell: bash
        run: cat gradle.properties >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Publish
        env:
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        #run: ./gradlew assemble modrinth publishAllPublicationsToHangar --stacktrace
        run: ./gradlew assemble modrinth --stacktrace